version: '3.4'

services:
  starkalpine.liftstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  starkalpine.frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LiftStatusClientOptions__BaseAddress=http://starkalpine.liftstatus/
