version: '3.4'

services:
  starkalpine.liftstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ResortOptions__TimeZone=Europe/Zurich
      - ResortOptions__OpeningTime=0900
      - ResortOptions__ClosingTime=1600

  starkalpine.frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LiftStatusClientOptions__BaseAddress=http://starkalpine.liftstatus/
