version: '3.4'

services:
  starkalpine.liftstatus:
    build:
      context: .
      dockerfile: StarkAlpine.LiftStatus.Api/Dockerfile
    ports:
      - "8080:80"

  starkalpine.frontend:
    build:
      context: .
      dockerfile: StarkAlpine.FrontEnd/Dockerfile
    ports:
      - "8081:80"
