apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifstatus
  labels:
    app: stark-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      service: liftstatus
  template:
    metadata:
      labels:
        app: stark-alpine
        service: liftstatus
    spec:
      containers:
        - name: liftstatus
          image: docker.io/alasdairstarkamido/starkalpineliftstatus:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ResortOptions__TimeZone
              value: Europe/Zurich
            - name: ResortOptions__OpeningTime
              value: '0900'
            - name: ResortOptions__ClosingTime
              value: '1600'
---
apiVersion: v1
kind: Service
metadata:
  name: liftstatus
  labels:
    app: stark-alpine
    service: liftstatus
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: liftstatus