apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: stark-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        app: stark-alpine
        service: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/alasdairstarkamido/starkalpinefrontend:1629904440
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: LiftStatusClientOptions__BaseAddress
              value: http://liftstatus
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: stark-alpine
    service: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: frontend