name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set timestamp environment variable for tagging
      run: echo "TAG=$(date +%s)" >> ${GITHUB_ENV}
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: alasdairstarkamido
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Build the Docker image for the front end
      run: docker build . --file StarkAlpine.FrontEnd/Dockerfile --tag alasdairstark/starkalpinefrontend:${{ env.TAG }}
    - name: Build the Docker image for the lift status API
      run: docker build . --file StarkAlpine.LiftStatus.Api/Dockerfile --tag alasdairstark/starkalpineliftstatus:${{ env.TAG }}
    - name: Push the Docker image for the front end
      run: docker push alasdairstarkamido/starkalpinefrontend:${{ env.TAG }}
    - name: Push the Docker image for the lift status API
      run: docker push alasdairstarkamido/starkalpineliftstatus:${{ env.TAG }}
