name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for the front end
      run: docker build . --file StarkAlpine.FrontEnd/Dockerfile --tag starkalpinefrontend:$(date +%s)
    - name: Build the Docker image for the lift status API
      run: docker build . --file StarkAlpine.LiftStatus.Api/Dockerfile --tag starkalpineliftstatus:$(date +%s)
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: alasdairstarkamido
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
